# Generated by Django 2.0 on 2017-12-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20171231_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(upload_to='featued_image'),
        ),
    ]
