# Generated by Django 2.0 on 2018-01-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('headline', models.CharField(max_length=50)),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('normal', 'Normal')], max_length=6)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='My_Life')),
            ],
        ),
    ]
