# Generated by Django 2.0 on 2018-01-10 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribersemail',
            options={'verbose_name': "Subscriber's Email", 'verbose_name_plural': "Subscriber's Emails"},
        ),
    ]
